[tox]
env_list = lint, smoke
skip_missing_interpreters = true

[testenv:lint]
description = run linting for all MongoDB snaps
skip_install = true
allowlist_externals =
    tox
commands =
    tox -c mongodb/snaps/slim/mongodb-server-replicaset/tox.ini -e lint
    tox -c mongodb/snaps/slim/mongodb-server-sharded/tox.ini -e lint
    tox -c mongos/snaps/slim/mongos/tox.ini -e lint
    tox -c mongodb/rocks/slim/mongodb-server-sharded/tox.ini -e lint
