[tox]
env_list = lint, smoke
skip_missing_interpreters = true

[testenv:lint]
description = run linting for all MongoDB snaps
skip_install = true
allowlist_externals =
    tox
commands =
    tox -c mongodb/snaps/charmed/tox.ini -e lint
    tox -c mongodb/rocks/charmed/tox.ini -e lint
