#!/usr/bin/env bash
# Refresh hook for mongos snap

set -eux

export ETC="${SNAP_DATA}"/etc
export CONF="${ETC}"/mongod
export MONGOS_CONFIG_FILE="${CONF}"/mongos.conf
export KEYFILE="${ETC}"/mongodb-keyfile

update_keyfile_path() {
    local config_file="$1"

    if [ "$(id -u)" = "0" ]; then
        "${SNAP}/usr/bin/setpriv" \
            --clear-groups \
            --reuid snap_daemon \
            --regid snap_daemon \
            -- \
            yq -i ".security.keyFile = \"${KEYFILE}\"" "${config_file}"
    else
        yq -i ".security.keyFile = \"${KEYFILE}\"" "${config_file}"
    fi
}

if [ -f "${MONGOS_CONFIG_FILE}" ]; then
    update_keyfile_path "${MONGOS_CONFIG_FILE}"
fi
