#!/usr/bin/env bash
# Installation hook for mongodb-server-sharded snap

set -eux

export PYTHONPATH="${SNAP}"/usr/lib/python3/dist-packages/
export ETC="$SNAP_DATA"/etc
export CONF="${SNAP_DATA}"/etc/mongod
export GSS="${SNAP_DATA}"/etc/gss
export DATA="${SNAP_COMMON}"/var/lib/mongodb
export LOGS="${SNAP_COMMON}"/var/log/mongodb
export RUN="${SNAP_COMMON}"/run
export HOME_DIR="${SNAP_DATA}"/home
export MONGO_CONFIG_FILE="${CONF}"/mongod.conf
export MONGOS_CONFIG_FILE="${CONF}"/mongos.conf
export KEYFILE="${ETC}"/mongodb-keyfile
export KEYFILE_CONFIG="$(dirname "${SNAP_DATA}")/current/etc/mongodb-keyfile"
export MONGOD_PID_FILE="${RUN}/mongod.pid"
export MONGOS_PID_FILE="${RUN}/mongos.pid"

# Create the necessary parent directories 
mkdir -p $DATA
mkdir -p $LOGS
mkdir -p $CONF
mkdir -p $GSS
mkdir -p $RUN
mkdir -p "${HOME_DIR}/.cache" "${HOME_DIR}/.config"
chown 584788:root "${HOME_DIR}" "${HOME_DIR}/.cache" "${HOME_DIR}/.config"

"${SNAP}/usr/bin/setpriv" \
    --clear-groups \
    --reuid snap_daemon \
    --regid snap_daemon \
    -- \
    mkdir -p "${HOME_DIR}/.mongodb/mongosh"

chown 584788:root "${GSS}"
"${SNAP}/usr/bin/setpriv" \
    --clear-groups \
    --reuid snap_daemon \
    --regid snap_daemon \
    -- \
    bash -euo pipefail -c 'chmod 755 "$1"; touch "$1/mech"; chmod 644 "$1/mech"' bash "${GSS}"

# If we just created the directory, we set up permissions
if [ stat -c '%u' "$DATA" == 0 ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod 750 "${DATA}"
fi

# If we just created the directory, we set up permissions
if [ stat -c '%u' "$LOGS" == 0 ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod g+s "$LOGS"/*
fi

# If we just created the directory, we set up permissions
if [ stat -c '%u' "$RUN" == 0 ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod 750 "${RUN}"
fi

chown -R 584788:root "${SNAP_COMMON}"/*

# Copy over the mongod.conf and create needed directories/files
echo "mongod configuration file does not exist."
echo "copying default config to ${MONGO_CONFIG_FILE}"
cp -r ${SNAP}/etc/mongod.conf ${MONGO_CONFIG_FILE}

# mongod.conf default values are not consistent with the snap directory system.
yq -i -Y ".processManagement.fork = false" ${MONGO_CONFIG_FILE}
yq -i -Y ".security.keyFile = \"${KEYFILE_CONFIG}\"" "${MONGO_CONFIG_FILE}"
yq -i -Y ".processManagement.pidFilePath = \"${MONGOD_PID_FILE}\"" "${MONGO_CONFIG_FILE}"
yq -i -Y ".systemLog.path = \"${LOGS}/mongod.log\"" ${MONGO_CONFIG_FILE}
yq -i -Y ".storage.dbPath = \"${DATA}\"" ${MONGO_CONFIG_FILE}
yq -i -Y "del(.storage.journal)" ${MONGO_CONFIG_FILE}
sed -i '/^#security:$/d' "${MONGO_CONFIG_FILE}"
sed -i '/^security:$/i #security:' "${MONGO_CONFIG_FILE}"

# Copy over the mongos.conf and create needed directories/files
echo "mongos configuration file does not exist."
echo "copying default config to ${MONGOS_CONFIG_FILE}"
cp -r ${MONGO_CONFIG_FILE} ${MONGOS_CONFIG_FILE}

# mongos.conf default values are not consistent with the snap directory system.
yq -i -Y ".processManagement.pidFilePath = \"${MONGOS_PID_FILE}\"" "${MONGOS_CONFIG_FILE}"
yq -i -Y ".systemLog.path = \"${LOGS}/mongos.log\"" ${MONGOS_CONFIG_FILE}
yq -i -Y ".net.port = 27018" ${MONGOS_CONFIG_FILE}
yq -i -Y "del(.storage)" ${MONGOS_CONFIG_FILE}

# Change ownership of snap directories to allow snap_daemon to read/write
chown -R 584788:root "${SNAP_DATA}"/*

if [ ! -s "${KEYFILE}" ]; then
    "${SNAP}/usr/bin/setpriv" \
        --clear-groups \
        --reuid snap_daemon \
        --regid snap_daemon \
        -- \
        bash -euo pipefail -c '. "${SNAP}/keyfile-common.sh"; generate_keyfile'
fi
