#!/usr/bin/env bash
# Installation hook for charmed-mongodb snap

set -eux

export PYTHONPATH="${SNAP}"/usr/lib/python3/dist-packages/
export ETC="$SNAP_DATA"/etc
export CONF="${SNAP_DATA}"/etc/mongod
export GSS="${SNAP_DATA}"/etc/gss
export PBM_CONF="${SNAP_DATA}"/etc/pbm
export VAULT_CONF="${SNAP_DATA}"/etc/vault
export DATA="${SNAP_COMMON}"/var/lib/mongodb
export LOGS="${SNAP_COMMON}"/var/log/mongodb
export VAULT_LOGS="${SNAP_COMMON}"/var/log/vault
export HOME_DIR="${SNAP_DATA}"/home
export MONGO_CONFIG_FILE="${CONF}"/mongod.conf
export MONGOS_CONFIG_FILE="${CONF}"/mongos.conf
export VAULT_CONFIG_FILE="${VAULT_CONF}"/vault-agent.hcl

# Create the necessary parent directories 
mkdir -p $DATA
mkdir -p $LOGS
mkdir -p $VAULT_LOGS
mkdir -p $PBM_CONF
mkdir -p $CONF
mkdir -p $GSS
mkdir -p $VAULT_CONF

mkdir -p "${HOME_DIR}/.cache" "${HOME_DIR}/.config" "${HOME_DIR}/.mongodb/mongosh"
chown 584788:root "${GSS}"
"${SNAP}/usr/bin/setpriv" \
    --clear-groups \
    --reuid snap_daemon \
    --regid snap_daemon \
    -- \
    bash -euo pipefail -c 'chmod 755 "$1"; touch "$1/mech"; chmod 644 "$1/mech"' bash "${GSS}"

# If we just created the directory, we set up permissions
if [ stat -c '%u' "$DATA" == 0 ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod 750 "${DATA}"
fi

# If we just created the directory, we set up permissions
if [ stat -c '%u' "$LOGS" == 0 ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod g+s "$LOGS"/*
fi

if [ stat -c '%u' "$VAULT_LOGS" == 0 ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod g+s "$VAULT_LOGS"/*
fi

chown -R 584788:root "${SNAP_COMMON}"/*

# Copy over the mongod.conf and create needed directories/files
echo "mongod configuration file does not exist."
echo "copying default config to ${MONGO_CONFIG_FILE}"
cp -r ${SNAP}/etc/mongod.conf ${MONGO_CONFIG_FILE}

# Copy over the mongos.conf and create needed directories/files
echo "mongos configuration file does not exist."
echo "copying default config to ${MONGOS_CONFIG_FILE}"
cp -r ${SNAP}/etc/mongod.conf ${MONGOS_CONFIG_FILE}

echo "vault configuration file does not exist."
echo "copying default config to ${VAULT_CONFIG_FILE}"
cp -r ${SNAP}/vault.hcl ${VAULT_CONFIG_FILE}

# mongod.conf default values are not consistent with the snap directory system.
yq -i -Y ".processManagement.fork = false" ${MONGO_CONFIG_FILE}
yq -i -Y "del(.processManagement.pidFilePath)" ${MONGO_CONFIG_FILE}
yq -i -Y ".systemLog.path = \"${LOGS}/mongod.log\"" ${MONGO_CONFIG_FILE}
yq -i -Y ".storage.dbPath = \"${DATA}\"" ${MONGO_CONFIG_FILE}
yq -i -Y "del(.storage.journal)" ${MONGO_CONFIG_FILE}

# mongos.conf default values are not consistent with the snap directory system.
yq -i -Y ".processManagement.fork = false" ${MONGOS_CONFIG_FILE}
yq -i -Y ".systemLog.path = \"${LOGS}/mongod.log\"" ${MONGOS_CONFIG_FILE}
yq -i -Y ".net.port = 27018" ${MONGOS_CONFIG_FILE}
yq -i -Y "del(.storage)" ${MONGOS_CONFIG_FILE}

# Copy over the LDAP configuration to keep isolation.
cp -r "${SNAP}/etc/ldap/" "${ETC}"

# Change ownership of snap directories to allow snap_daemon to read/write
chown -R 584788:root "${SNAP_DATA}"/*
