#!/usr/bin/env bash
# post-refresh hook for charmed-mongodb snap

set -eux

export CONF="${SNAP_DATA}/etc/mongod"
export VAULT_CONF="${SNAP_DATA}/etc/vault"
export ETC="${SNAP_DATA}/etc/"
export MONGOS_CONFIG_FILE="${CONF}/mongos.conf"
export LOGS="${SNAP_COMMON}/var/log/mongodb"
export VAULT_LOGS="${SNAP_COMMON}/var/log/vault"
export LDAP_CONF_DIR="${SNAP_DATA}/etc/ldap/"
export VAULT_CONFIG_FILE="${VAULT_CONF}/vault-agent.hcl"

if [ ! -f $MONGOS_CONFIG_FILE ]; then
    # Copy over the mongos.conf and create needed directories/files
    echo "mongos configuration file does not exist."
    echo "copying default config to ${MONGOS_CONFIG_FILE}"

    # Grant permissions on $CONF
    chown root:snap_daemon "$CONF"

    cp "${SNAP}/etc/mongod.conf" "${MONGOS_CONFIG_FILE}"

    # mongos.conf default values are not consistent with the snap directory system.
    yq -i ".processManagement.fork = false" ${MONGOS_CONFIG_FILE}
    yq -i ".systemLog.path = \"${LOGS}/mongod.log\"" ${MONGOS_CONFIG_FILE}
    yq -i ".net.port = 27018" ${MONGOS_CONFIG_FILE}
    yq -i "del(.storage)" ${MONGOS_CONFIG_FILE}

    # Change ownership of snap directories to allow snap_daemon to read/write
    chown -R 584788:root "${CONF}"
fi

if  [ ! -d $LDAP_CONF_DIR ]; then
    # Copy over the LDAP configuration
    echo "ldap configuration does not exist."
    echo "copying default config to ${LDAP_CONF_DIR}."

    # Grant enough permissions to create files
    chown root:snap_daemon "$ETC"

    cp -r "${SNAP}/etc/ldap/" "${ETC}"

    # Change ownership of snap directories to allow snap_daemon to read/write
    chown -R 584788:root "${ETC}"
fi

if [ ! -d $VAULT_CONF ]; then
    # Copy over the vault configuration
    echo "vault configuration does not exist."
    echo "copying default config to ${VAULT_CONF}."

    # Grant enough permissions to create files
    chown root:snap_daemon "$ETC"

    mkdir -p $VAULT_CONF
    cp -r "${SNAP}/vault.hcl" "${VAULT_CONFIG_FILE}"

    # Change ownership of snap directories to allow snap_daemon to read/write
    chown -R 584788:root "${ETC}"
fi
